import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'

import HeroView from '../components/views/heroView'
import SkillsView from '../components/views/skillsView'
import ProjectsView from '../components/views/projectsView'
import ContactView from '../components/views/contactView'
export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={`${styles.main}`}>
          <HeroView />
          <SkillsView />
          <ProjectsView />
          <ContactView />
        </main>
      </div>
    </Layout>
  )
}
